INSERT INTO USERROLE (ROLENAME, CANADDPRODUCT, CANEDITPRODUCT, CANDELETEPRODUCT, CANVIEWINVENTORY, CANEDITINVENTORY, CANVIEWREPORTS, CANMODIFYUSERS)
VALUES 
('Admin', 1, 1, 1, 1, 1, 1, 1),
('Manager', 1, 1, 0, 1, 1, 1, 0),
('Staff', 0, 0, 0, 1, 0, 0, 0);
GO --executed

